import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ppNeue = localFont({
  src: "./fonts/PPNeueMontreal.otf",
  variable: "--font-ppneue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ppNeue.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
